apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: test1.example.com
  namespace: default

spec:
  secretName: test1.example.com-tls
  issuerRef:
    name: letsencrypt-staging-cluster-issuer
    kind: ClusterIssuer
  commonName: test1.example.com
  dnsNames:
      - test1.example.com
      - test2.example.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - test1.example.com
      - test2.example.com
